/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-16 11:15:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.rays.bean.UserBean;
import java.util.Iterator;
import java.util.List;
import com.rays.bean.UserBean;

public final class UserList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1710587726807L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1710587176273L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.rays.bean.UserBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

		UserBean user = (UserBean) session.getAttribute("user");
		String msg = "hii, ";
		if (user != null) {

			msg += user.getFirstName() + " " + user.getLastName();

		} else {

			msg += "guest";

		}
	
      out.write("\n");
      out.write("	<br>\n");
      out.write("	<a href=\"UserRegistration.jsp\">signUp</a> |\n");
      out.write("	");

		if (user != null) {
	
      out.write("\n");
      out.write("	<a href=\"UserListCtl\">UserList</a> |\n");
      out.write("	<a href=\"LoginCtl?operation=logout\">logout</a>\n");
      out.write("	");

		} else {
	
      out.write("\n");
      out.write("	<a href=\"LoginCtl\">login</a>\n");
      out.write("	");

		}
	
      out.write("\n");
      out.write("\n");
      out.write("	<h4>");
      out.print(msg);
      out.write("</h4>\n");
      out.write("	<hr>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('	');

		int pageNo = (int) request.getAttribute("pageNo");
		String dmsg = (String) request.getAttribute("delete");
		List list = (List) request.getAttribute("userList");
		List nextList = (List) request.getAttribute("nextUser");
	
      out.write("\n");
      out.write("	<h1 align=\"center\">UserList</h1>\n");
      out.write("	");

		if (dmsg != null) {
	
      out.write("\n");
      out.write("	<font color=\"red\">");
      out.print(dmsg);
      out.write("</font>\n");
      out.write("	");

		}
	
      out.write("\n");
      out.write("	<form action=\"UserListCtl\" method=\"post\">\n");
      out.write("		<table style=\"width: 30%\">\n");
      out.write("			<tr>\n");
      out.write("				<td><input type=\"text\" name=\"firstName\"\n");
      out.write("					placeholder=\"Enter First Name\"></td>\n");
      out.write("				<td></td>\n");
      out.write("				<td><input type=\"submit\" name=\"operation\" value=\"search\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr></tr>\n");
      out.write("			<tr></tr>\n");
      out.write("			<tr></tr>\n");
      out.write("		</table>\n");
      out.write("		<table border=\"2\" width=\"100%\" align=\"center\">\n");
      out.write("			<tr>\n");
      out.write("				<th>Select</th>\n");
      out.write("				<th>Id</th>\n");
      out.write("				<th>FirstName</th>\n");
      out.write("				<th>LastName</th>\n");
      out.write("				<th>Email</th>\n");
      out.write("				<th>PhoneNo</th>\n");
      out.write("				<th>dob</th>\n");
      out.write("				<th>Gender</th>\n");
      out.write("				<th>Edit</th>\n");
      out.write("			</tr>\n");
      out.write("			");

				Iterator<UserBean> it = list.iterator();
				while (it.hasNext()) {

					UserBean bean = it.next();
			
      out.write("\n");
      out.write("			<tr align=\"center\">\n");
      out.write("				<td><input type=\"checkbox\" name=\"ids\" value=\"");
      out.print(bean.getId());
      out.write("\"></td>\n");
      out.write("				<td>");
      out.print(bean.getId());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getFirstName());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getLastName());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getLoginId());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getPhoneNo());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getDob());
      out.write("</td>\n");
      out.write("				<td>");
      out.print(bean.getGender());
      out.write("</td>\n");
      out.write("				<td><a href=\"UserRegistrationCtl?id=");
      out.print(bean.getId());
      out.write("\">edit</a></td>\n");
      out.write("			</tr>\n");
      out.write("			");

				}
			
      out.write("\n");
      out.write("		</table>\n");
      out.write("		<table style=\"width: 100%\">\n");
      out.write("			<tr>\n");
      out.write("				<td><input type=\"submit\" name=\"operation\" value=\"previous\"\n");
      out.write("					");
      out.print((pageNo != 1) ? "" : "disabled");
      out.write("></td>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<td align=\"center\"><input type=\"submit\" name=\"operation\"\n");
      out.write("					value=\"delete\"></td>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<td align=\"right\"><input type=\"submit\" name=\"operation\"\n");
      out.write("					value=\"next\" ");
      out.print((nextList.size() != 0) ? "" : "disabled");
      out.write("></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\">\n");
      out.write("	</form>\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#footer {\n");
      out.write("	position: fixed;\n");
      out.write("	left: 0;\n");
      out.write("	width: 100%;\n");
      out.write("	bottom: 0;\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div id=\"footer\">\n");
      out.write("		<CENTER>\n");
      out.write("			<hr>\n");
      out.write("			<H3>&copy; Copyrights RAYS Technologies</H3>\n");
      out.write("		</CENTER>\n");
      out.write("	</div>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
